// Code generated by make; DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: volumegroup/volumegroup.proto

package volumegroup

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateVolumeGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// suggested name for volume group (required for idempotency)
	// This field is REQUIRED.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// params passed from VolumeGroupClass
	// This field is OPTIONAL.
	Parameters map[string]string `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Secrets required by plugin to complete volume group creation
	// request.
	// This field is OPTIONAL. Refer to the `Secrets Requirements`
	// section on how to use this field.
	Secrets       map[string]string `protobuf:"bytes,3,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeGroupRequest) Reset() {
	*x = CreateVolumeGroupRequest{}
	mi := &file_volumegroup_volumegroup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeGroupRequest) ProtoMessage() {}

func (x *CreateVolumeGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_volumegroup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateVolumeGroupRequest) Descriptor() ([]byte, []int) {
	return file_volumegroup_volumegroup_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVolumeGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVolumeGroupRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *CreateVolumeGroupRequest) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type CreateVolumeGroupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contains all attributes of the newly created volume group.
	// This field is REQUIRED.
	VolumeGroup   *VolumeGroup `protobuf:"bytes,1,opt,name=volume_group,json=volumeGroup,proto3" json:"volume_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeGroupResponse) Reset() {
	*x = CreateVolumeGroupResponse{}
	mi := &file_volumegroup_volumegroup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeGroupResponse) ProtoMessage() {}

func (x *CreateVolumeGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_volumegroup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateVolumeGroupResponse) Descriptor() ([]byte, []int) {
	return file_volumegroup_volumegroup_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVolumeGroupResponse) GetVolumeGroup() *VolumeGroup {
	if x != nil {
		return x.VolumeGroup
	}
	return nil
}

type VolumeGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier for this volume group, generated by the plugin.
	// This field is REQUIRED.
	VolumeGroupId string `protobuf:"bytes,1,opt,name=volume_group_id,json=volumeGroupId,proto3" json:"volume_group_id,omitempty"`
	// Opaque static properties of the volume group.
	// This field is OPTIONAL.
	VolumeGroupContext map[string]string `protobuf:"bytes,2,rep,name=volume_group_context,json=volumeGroupContext,proto3" json:"volume_group_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Underlying volumes in this group. The same definition in CSI
	// Volume.
	// This field is OPTIONAL.
	// To support the creation of an empty group, this list can be empty.
	// However, this field is not empty in the following cases:
	//   - Response from ListVolumeGroups or ControllerGetVolumeGroup if the
	//     VolumeGroup is not empty.
	//   - Response from ModifyVolumeGroupMembership if the
	//     VolumeGroup is not empty after modification.
	Volumes       []*VgVolume `protobuf:"bytes,3,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeGroup) Reset() {
	*x = VolumeGroup{}
	mi := &file_volumegroup_volumegroup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeGroup) ProtoMessage() {}

func (x *VolumeGroup) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_volumegroup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeGroup.ProtoReflect.Descriptor instead.
func (*VolumeGroup) Descriptor() ([]byte, []int) {
	return file_volumegroup_volumegroup_proto_rawDescGZIP(), []int{2}
}

func (x *VolumeGroup) GetVolumeGroupId() string {
	if x != nil {
		return x.VolumeGroupId
	}
	return ""
}

func (x *VolumeGroup) GetVolumeGroupContext() map[string]string {
	if x != nil {
		return x.VolumeGroupContext
	}
	return nil
}

func (x *VolumeGroup) GetVolumes() []*VgVolume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

// Information about a specific volume.
type VgVolume struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The capacity of the volume in bytes. This field is OPTIONAL. If not
	// set (value of 0), it indicates that the capacity of the volume is
	// unknown (e.g., NFS share).
	// The value of this field MUST NOT be negative.
	CapacityBytes int64 `protobuf:"varint,1,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	// The identifier for this volume, generated by the plugin.
	// This field is REQUIRED.
	// This field MUST contain enough information to uniquely identify
	// this specific volume vs all other volumes supported by this plugin.
	// This field SHALL be used by the CO in subsequent calls to refer to
	// this volume.
	// The SP is NOT responsible for global uniqueness of volume_id across
	// multiple SPs.
	VolumeId string `protobuf:"bytes,2,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	// Opaque static properties of the volume. SP MAY use this field to
	// ensure subsequent volume validation and publishing calls have
	// contextual information.
	// The contents of this field SHALL be opaque to a CO.
	// The contents of this field SHALL NOT be mutable.
	// The contents of this field SHALL be safe for the CO to cache.
	// The contents of this field SHOULD NOT contain sensitive
	// information.
	// The contents of this field SHOULD NOT be used for uniquely
	// identifying a volume. The `volume_id` alone SHOULD be sufficient to
	// identify the volume.
	// A volume uniquely identified by `volume_id` SHALL always report the
	// same volume_context.
	// This field is OPTIONAL and when present MUST be passed to volume
	// validation and publishing calls.
	VolumeContext map[string]string `protobuf:"bytes,3,rep,name=volume_context,json=volumeContext,proto3" json:"volume_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// If specified, indicates that the volume is not empty and is
	// pre-populated with data from the specified source.
	// This field is OPTIONAL.
	ContentSource *VgVolumeContentSource `protobuf:"bytes,4,opt,name=content_source,json=contentSource,proto3" json:"content_source,omitempty"`
	// Specifies where (regions, zones, racks, etc.) the provisioned
	// volume is accessible from.
	// A plugin that returns this field MUST also set the
	// VOLUME_ACCESSIBILITY_CONSTRAINTS plugin capability.
	// An SP MAY specify multiple topologies to indicate the volume is
	// accessible from multiple locations.
	// COs MAY use this information along with the topology information
	// returned by NodeGetInfo to ensure that a given volume is accessible
	// from a given node when scheduling workloads.
	// This field is OPTIONAL. If it is not specified, the CO MAY assume
	// the volume is equally accessible from all nodes in the cluster and
	// MAY schedule workloads referencing the volume on any available
	// node.
	//
	// Example 1:
	//
	//	accessible_topology = {"region": "R1", "zone": "Z2"}
	//
	// Indicates a volume accessible only from the "region" "R1" and the
	// "zone" "Z2".
	//
	// Example 2:
	//
	//	accessible_topology =
	//	  {"region": "R1", "zone": "Z2"},
	//	  {"region": "R1", "zone": "Z3"}
	//
	// Indicates a volume accessible from both "zone" "Z2" and "zone" "Z3"
	// in the "region" "R1".
	AccessibleTopology []*VgTopology `protobuf:"bytes,5,rep,name=accessible_topology,json=accessibleTopology,proto3" json:"accessible_topology,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VgVolume) Reset() {
	*x = VgVolume{}
	mi := &file_volumegroup_volumegroup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VgVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VgVolume) ProtoMessage() {}

func (x *VgVolume) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_volumegroup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VgVolume.ProtoReflect.Descriptor instead.
func (*VgVolume) Descriptor() ([]byte, []int) {
	return file_volumegroup_volumegroup_proto_rawDescGZIP(), []int{3}
}

func (x *VgVolume) GetCapacityBytes() int64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *VgVolume) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *VgVolume) GetVolumeContext() map[string]string {
	if x != nil {
		return x.VolumeContext
	}
	return nil
}

func (x *VgVolume) GetContentSource() *VgVolumeContentSource {
	if x != nil {
		return x.ContentSource
	}
	return nil
}

func (x *VgVolume) GetAccessibleTopology() []*VgTopology {
	if x != nil {
		return x.AccessibleTopology
	}
	return nil
}

type VgTopology struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      map[string]string      `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VgTopology) Reset() {
	*x = VgTopology{}
	mi := &file_volumegroup_volumegroup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VgTopology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VgTopology) ProtoMessage() {}

func (x *VgTopology) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_volumegroup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VgTopology.ProtoReflect.Descriptor instead.
func (*VgTopology) Descriptor() ([]byte, []int) {
	return file_volumegroup_volumegroup_proto_rawDescGZIP(), []int{4}
}

func (x *VgTopology) GetSegments() map[string]string {
	if x != nil {
		return x.Segments
	}
	return nil
}

type VgVolumeContentSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*VgVolumeContentSource_Snapshot
	//	*VgVolumeContentSource_Volume
	Type          isVgVolumeContentSource_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VgVolumeContentSource) Reset() {
	*x = VgVolumeContentSource{}
	mi := &file_volumegroup_volumegroup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VgVolumeContentSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VgVolumeContentSource) ProtoMessage() {}

func (x *VgVolumeContentSource) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_volumegroup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VgVolumeContentSource.ProtoReflect.Descriptor instead.
func (*VgVolumeContentSource) Descriptor() ([]byte, []int) {
	return file_volumegroup_volumegroup_proto_rawDescGZIP(), []int{5}
}

func (x *VgVolumeContentSource) GetType() isVgVolumeContentSource_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *VgVolumeContentSource) GetSnapshot() *VgVolumeContentSource_SnapshotSource {
	if x != nil {
		if x, ok := x.Type.(*VgVolumeContentSource_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *VgVolumeContentSource) GetVolume() *VgVolumeContentSource_VolumeSource {
	if x != nil {
		if x, ok := x.Type.(*VgVolumeContentSource_Volume); ok {
			return x.Volume
		}
	}
	return nil
}

type isVgVolumeContentSource_Type interface {
	isVgVolumeContentSource_Type()
}

type VgVolumeContentSource_Snapshot struct {
	Snapshot *VgVolumeContentSource_SnapshotSource `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type VgVolumeContentSource_Volume struct {
	Volume *VgVolumeContentSource_VolumeSource `protobuf:"bytes,2,opt,name=volume,proto3,oneof"`
}

func (*VgVolumeContentSource_Snapshot) isVgVolumeContentSource_Type() {}

func (*VgVolumeContentSource_Volume) isVgVolumeContentSource_Type() {}

type DeleteVolumeGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the volume group to be deleted.
	// This field is REQUIRED.
	VolumeGroupId string `protobuf:"bytes,1,opt,name=volume_group_id,json=volumeGroupId,proto3" json:"volume_group_id,omitempty"`
	// Secrets required by plugin to complete volume group
	// deletion request.
	// This field is OPTIONAL. Refer to the `Secrets Requirements`
	// section on how to use this field.
	Secrets       map[string]string `protobuf:"bytes,2,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVolumeGroupRequest) Reset() {
	*x = DeleteVolumeGroupRequest{}
	mi := &file_volumegroup_volumegroup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVolumeGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVolumeGroupRequest) ProtoMessage() {}

func (x *DeleteVolumeGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_volumegroup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVolumeGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteVolumeGroupRequest) Descriptor() ([]byte, []int) {
	return file_volumegroup_volumegroup_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteVolumeGroupRequest) GetVolumeGroupId() string {
	if x != nil {
		return x.VolumeGroupId
	}
	return ""
}

func (x *DeleteVolumeGroupRequest) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type DeleteVolumeGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVolumeGroupResponse) Reset() {
	*x = DeleteVolumeGroupResponse{}
	mi := &file_volumegroup_volumegroup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVolumeGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVolumeGroupResponse) ProtoMessage() {}

func (x *DeleteVolumeGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_volumegroup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVolumeGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteVolumeGroupResponse) Descriptor() ([]byte, []int) {
	return file_volumegroup_volumegroup_proto_rawDescGZIP(), []int{7}
}

type ModifyVolumeGroupMembershipRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the volume group to be modified.
	// This field is REQUIRED.
	VolumeGroupId string `protobuf:"bytes,1,opt,name=volume_group_id,json=volumeGroupId,proto3" json:"volume_group_id,omitempty"`
	// Specify volume_ids that will be in the modified volume group.
	// This list will be compared with the volume_ids in the existing
	// group.
	// New ones will be added and missing ones will be removed.
	// If no volume_ids are provided, all existing volumes will
	// be removed from the group.
	// This field is OPTIONAL.
	VolumeIds []string `protobuf:"bytes,2,rep,name=volume_ids,json=volumeIds,proto3" json:"volume_ids,omitempty"`
	// Secrets required by plugin to complete volume group
	// modification request.
	// This field is OPTIONAL. Refer to the `Secrets Requirements`
	// section on how to use this field.
	Secrets       map[string]string `protobuf:"bytes,3,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyVolumeGroupMembershipRequest) Reset() {
	*x = ModifyVolumeGroupMembershipRequest{}
	mi := &file_volumegroup_volumegroup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyVolumeGroupMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyVolumeGroupMembershipRequest) ProtoMessage() {}

func (x *ModifyVolumeGroupMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_volumegroup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyVolumeGroupMembershipRequest.ProtoReflect.Descriptor instead.
func (*ModifyVolumeGroupMembershipRequest) Descriptor() ([]byte, []int) {
	return file_volumegroup_volumegroup_proto_rawDescGZIP(), []int{8}
}

func (x *ModifyVolumeGroupMembershipRequest) GetVolumeGroupId() string {
	if x != nil {
		return x.VolumeGroupId
	}
	return ""
}

func (x *ModifyVolumeGroupMembershipRequest) GetVolumeIds() []string {
	if x != nil {
		return x.VolumeIds
	}
	return nil
}

func (x *ModifyVolumeGroupMembershipRequest) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type ModifyVolumeGroupMembershipResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contains all attributes of the modified volume group.
	// This field is REQUIRED.
	VolumeGroup   *VolumeGroup `protobuf:"bytes,1,opt,name=volume_group,json=volumeGroup,proto3" json:"volume_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyVolumeGroupMembershipResponse) Reset() {
	*x = ModifyVolumeGroupMembershipResponse{}
	mi := &file_volumegroup_volumegroup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyVolumeGroupMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyVolumeGroupMembershipResponse) ProtoMessage() {}

func (x *ModifyVolumeGroupMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_volumegroup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyVolumeGroupMembershipResponse.ProtoReflect.Descriptor instead.
func (*ModifyVolumeGroupMembershipResponse) Descriptor() ([]byte, []int) {
	return file_volumegroup_volumegroup_proto_rawDescGZIP(), []int{9}
}

func (x *ModifyVolumeGroupMembershipResponse) GetVolumeGroup() *VolumeGroup {
	if x != nil {
		return x.VolumeGroup
	}
	return nil
}

type ControllerGetVolumeGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the volume group to fetch current volume group
	// information for.
	// This field is REQUIRED.
	VolumeGroupId string `protobuf:"bytes,1,opt,name=volume_group_id,json=volumeGroupId,proto3" json:"volume_group_id,omitempty"`
	// Secrets required by plugin to complete ControllerGetVolumeGroup
	// request.
	// This field is OPTIONAL. Refer to the `Secrets Requirements`
	// section on how to use this field.
	Secrets       map[string]string `protobuf:"bytes,2,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerGetVolumeGroupRequest) Reset() {
	*x = ControllerGetVolumeGroupRequest{}
	mi := &file_volumegroup_volumegroup_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerGetVolumeGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerGetVolumeGroupRequest) ProtoMessage() {}

func (x *ControllerGetVolumeGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_volumegroup_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerGetVolumeGroupRequest.ProtoReflect.Descriptor instead.
func (*ControllerGetVolumeGroupRequest) Descriptor() ([]byte, []int) {
	return file_volumegroup_volumegroup_proto_rawDescGZIP(), []int{10}
}

func (x *ControllerGetVolumeGroupRequest) GetVolumeGroupId() string {
	if x != nil {
		return x.VolumeGroupId
	}
	return ""
}

func (x *ControllerGetVolumeGroupRequest) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type ControllerGetVolumeGroupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field is REQUIRED
	VolumeGroup   *VolumeGroup `protobuf:"bytes,1,opt,name=volume_group,json=volumeGroup,proto3" json:"volume_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerGetVolumeGroupResponse) Reset() {
	*x = ControllerGetVolumeGroupResponse{}
	mi := &file_volumegroup_volumegroup_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerGetVolumeGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerGetVolumeGroupResponse) ProtoMessage() {}

func (x *ControllerGetVolumeGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_volumegroup_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerGetVolumeGroupResponse.ProtoReflect.Descriptor instead.
func (*ControllerGetVolumeGroupResponse) Descriptor() ([]byte, []int) {
	return file_volumegroup_volumegroup_proto_rawDescGZIP(), []int{11}
}

func (x *ControllerGetVolumeGroupResponse) GetVolumeGroup() *VolumeGroup {
	if x != nil {
		return x.VolumeGroup
	}
	return nil
}

type ListVolumeGroupsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If specified (non-zero value), the Plugin MUST NOT return more
	// entries than this number in the response. If the actual number of
	// entries is more than this number, the Plugin MUST set `next_token`
	// in the response which can be used to get the next page of entries
	// in the subsequent `ListVolumeGroups` call. This field is OPTIONAL.
	// If not specified (zero value), it means there is no restriction on
	// the number of entries that can be returned.
	// The value of this field MUST NOT be negative.
	MaxEntries int32 `protobuf:"varint,1,opt,name=max_entries,json=maxEntries,proto3" json:"max_entries,omitempty"`
	// A token to specify where to start paginating. Set this field to
	// `next_token` returned by a previous `ListVolumeGroups` call to get
	// the next page of entries. This field is OPTIONAL.
	// An empty string is equal to an unspecified field value.
	StartingToken string `protobuf:"bytes,2,opt,name=starting_token,json=startingToken,proto3" json:"starting_token,omitempty"`
	// Secrets required by plugin to complete ListVolumeGroup request.
	// This field is OPTIONAL. Refer to the `Secrets Requirements`
	// section on how to use this field.
	Secrets       map[string]string `protobuf:"bytes,3,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVolumeGroupsRequest) Reset() {
	*x = ListVolumeGroupsRequest{}
	mi := &file_volumegroup_volumegroup_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVolumeGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolumeGroupsRequest) ProtoMessage() {}

func (x *ListVolumeGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_volumegroup_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolumeGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListVolumeGroupsRequest) Descriptor() ([]byte, []int) {
	return file_volumegroup_volumegroup_proto_rawDescGZIP(), []int{12}
}

func (x *ListVolumeGroupsRequest) GetMaxEntries() int32 {
	if x != nil {
		return x.MaxEntries
	}
	return 0
}

func (x *ListVolumeGroupsRequest) GetStartingToken() string {
	if x != nil {
		return x.StartingToken
	}
	return ""
}

func (x *ListVolumeGroupsRequest) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type ListVolumeGroupsResponse struct {
	state   protoimpl.MessageState            `protogen:"open.v1"`
	Entries []*ListVolumeGroupsResponse_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// This token allows you to get the next page of entries for
	// `ListVolumeGroups` request. If the number of entries is larger than
	// `max_entries`, use the `next_token` as a value for the
	// `starting_token` field in the next `ListVolumeGroups` request. This
	// field is OPTIONAL.
	// An empty string is equal to an unspecified field value.
	NextToken     string `protobuf:"bytes,2,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVolumeGroupsResponse) Reset() {
	*x = ListVolumeGroupsResponse{}
	mi := &file_volumegroup_volumegroup_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVolumeGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolumeGroupsResponse) ProtoMessage() {}

func (x *ListVolumeGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_volumegroup_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolumeGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListVolumeGroupsResponse) Descriptor() ([]byte, []int) {
	return file_volumegroup_volumegroup_proto_rawDescGZIP(), []int{13}
}

func (x *ListVolumeGroupsResponse) GetEntries() []*ListVolumeGroupsResponse_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListVolumeGroupsResponse) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

type VgVolumeContentSource_SnapshotSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contains identity information for the existing source snapshot.
	// This field is REQUIRED. Plugin is REQUIRED to support creating
	// volume from snapshot if it supports the capability
	// CREATE_DELETE_SNAPSHOT.
	SnapshotId    string `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VgVolumeContentSource_SnapshotSource) Reset() {
	*x = VgVolumeContentSource_SnapshotSource{}
	mi := &file_volumegroup_volumegroup_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VgVolumeContentSource_SnapshotSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VgVolumeContentSource_SnapshotSource) ProtoMessage() {}

func (x *VgVolumeContentSource_SnapshotSource) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_volumegroup_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VgVolumeContentSource_SnapshotSource.ProtoReflect.Descriptor instead.
func (*VgVolumeContentSource_SnapshotSource) Descriptor() ([]byte, []int) {
	return file_volumegroup_volumegroup_proto_rawDescGZIP(), []int{5, 0}
}

func (x *VgVolumeContentSource_SnapshotSource) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type VgVolumeContentSource_VolumeSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contains identity information for the existing source volume.
	// This field is REQUIRED. Plugins reporting CLONE_VOLUME
	// capability MUST support creating a volume from another volume.
	VolumeId      string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VgVolumeContentSource_VolumeSource) Reset() {
	*x = VgVolumeContentSource_VolumeSource{}
	mi := &file_volumegroup_volumegroup_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VgVolumeContentSource_VolumeSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VgVolumeContentSource_VolumeSource) ProtoMessage() {}

func (x *VgVolumeContentSource_VolumeSource) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_volumegroup_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VgVolumeContentSource_VolumeSource.ProtoReflect.Descriptor instead.
func (*VgVolumeContentSource_VolumeSource) Descriptor() ([]byte, []int) {
	return file_volumegroup_volumegroup_proto_rawDescGZIP(), []int{5, 1}
}

func (x *VgVolumeContentSource_VolumeSource) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type ListVolumeGroupsResponse_Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field is REQUIRED
	VolumeGroup   *VolumeGroup `protobuf:"bytes,1,opt,name=volume_group,json=volumeGroup,proto3" json:"volume_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVolumeGroupsResponse_Entry) Reset() {
	*x = ListVolumeGroupsResponse_Entry{}
	mi := &file_volumegroup_volumegroup_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVolumeGroupsResponse_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolumeGroupsResponse_Entry) ProtoMessage() {}

func (x *ListVolumeGroupsResponse_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_volumegroup_volumegroup_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolumeGroupsResponse_Entry.ProtoReflect.Descriptor instead.
func (*ListVolumeGroupsResponse_Entry) Descriptor() ([]byte, []int) {
	return file_volumegroup_volumegroup_proto_rawDescGZIP(), []int{13, 0}
}

func (x *ListVolumeGroupsResponse_Entry) GetVolumeGroup() *VolumeGroup {
	if x != nil {
		return x.VolumeGroup
	}
	return nil
}

var file_volumegroup_volumegroup_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1101,
		Name:          "volumegroup.vg_csi_secret",
		Tag:           "varint,1101,opt,name=vg_csi_secret",
		Filename:      "volumegroup/volumegroup.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1102,
		Name:          "volumegroup.vg_alpha_message",
		Tag:           "varint,1102,opt,name=vg_alpha_message",
		Filename:      "volumegroup/volumegroup.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1102,
		Name:          "volumegroup.vg_alpha_method",
		Tag:           "varint,1102,opt,name=vg_alpha_method",
		Filename:      "volumegroup/volumegroup.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// Indicates that a field MAY contain information that is sensitive
	// and MUST be treated as such (e.g. not logged).
	//
	// optional bool vg_csi_secret = 1101;
	E_VgCsiSecret = &file_volumegroup_volumegroup_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// Indicates that this message is OPTIONAL and part of an experimental
	// API that may be deprecated and eventually removed between minor
	// releases.
	//
	// optional bool vg_alpha_message = 1102;
	E_VgAlphaMessage = &file_volumegroup_volumegroup_proto_extTypes[1]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// Indicates that this method is OPTIONAL and part of an experimental
	// API that may be deprecated and eventually removed between minor
	// releases.
	//
	// optional bool vg_alpha_method = 1102;
	E_VgAlphaMethod = &file_volumegroup_volumegroup_proto_extTypes[2]
)

var File_volumegroup_volumegroup_proto protoreflect.FileDescriptor

const file_volumegroup_volumegroup_proto_rawDesc = "" +
	"\n" +
	"\x1dvolumegroup/volumegroup.proto\x12\vvolumegroup\x1a google/protobuf/descriptor.proto\"\xd8\x02\n" +
	"\x18CreateVolumeGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12U\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v25.volumegroup.CreateVolumeGroupRequest.ParametersEntryR\n" +
	"parameters\x12Q\n" +
	"\asecrets\x18\x03 \x03(\v22.volumegroup.CreateVolumeGroupRequest.SecretsEntryB\x03\xe8D\x01R\asecrets\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\x03\xf0D\x01\"]\n" +
	"\x19CreateVolumeGroupResponse\x12;\n" +
	"\fvolume_group\x18\x01 \x01(\v2\x18.volumegroup.VolumeGroupR\vvolumeGroup:\x03\xf0D\x01\"\x96\x02\n" +
	"\vVolumeGroup\x12&\n" +
	"\x0fvolume_group_id\x18\x01 \x01(\tR\rvolumeGroupId\x12b\n" +
	"\x14volume_group_context\x18\x02 \x03(\v20.volumegroup.VolumeGroup.VolumeGroupContextEntryR\x12volumeGroupContext\x12/\n" +
	"\avolumes\x18\x03 \x03(\v2\x15.volumegroup.VgVolumeR\avolumes\x1aE\n" +
	"\x17VolumeGroupContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\x03\xf0D\x01\"\xf6\x02\n" +
	"\bVgVolume\x12%\n" +
	"\x0ecapacity_bytes\x18\x01 \x01(\x03R\rcapacityBytes\x12\x1b\n" +
	"\tvolume_id\x18\x02 \x01(\tR\bvolumeId\x12O\n" +
	"\x0evolume_context\x18\x03 \x03(\v2(.volumegroup.VgVolume.VolumeContextEntryR\rvolumeContext\x12I\n" +
	"\x0econtent_source\x18\x04 \x01(\v2\".volumegroup.VgVolumeContentSourceR\rcontentSource\x12H\n" +
	"\x13accessible_topology\x18\x05 \x03(\v2\x17.volumegroup.VgTopologyR\x12accessibleTopology\x1a@\n" +
	"\x12VolumeContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x01\n" +
	"\n" +
	"VgTopology\x12A\n" +
	"\bsegments\x18\x01 \x03(\v2%.volumegroup.VgTopology.SegmentsEntryR\bsegments\x1a;\n" +
	"\rSegmentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x02\n" +
	"\x15VgVolumeContentSource\x12O\n" +
	"\bsnapshot\x18\x01 \x01(\v21.volumegroup.VgVolumeContentSource.SnapshotSourceH\x00R\bsnapshot\x12I\n" +
	"\x06volume\x18\x02 \x01(\v2/.volumegroup.VgVolumeContentSource.VolumeSourceH\x00R\x06volume\x1a1\n" +
	"\x0eSnapshotSource\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x1a+\n" +
	"\fVolumeSource\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeIdB\x06\n" +
	"\x04type\"\xd6\x01\n" +
	"\x18DeleteVolumeGroupRequest\x12&\n" +
	"\x0fvolume_group_id\x18\x01 \x01(\tR\rvolumeGroupId\x12Q\n" +
	"\asecrets\x18\x02 \x03(\v22.volumegroup.DeleteVolumeGroupRequest.SecretsEntryB\x03\xe8D\x01R\asecrets\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\x03\xf0D\x01\" \n" +
	"\x19DeleteVolumeGroupResponse:\x03\xf0D\x01\"\x89\x02\n" +
	"\"ModifyVolumeGroupMembershipRequest\x12&\n" +
	"\x0fvolume_group_id\x18\x01 \x01(\tR\rvolumeGroupId\x12\x1d\n" +
	"\n" +
	"volume_ids\x18\x02 \x03(\tR\tvolumeIds\x12[\n" +
	"\asecrets\x18\x03 \x03(\v2<.volumegroup.ModifyVolumeGroupMembershipRequest.SecretsEntryB\x03\xe8D\x01R\asecrets\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\x03\xf0D\x01\"g\n" +
	"#ModifyVolumeGroupMembershipResponse\x12;\n" +
	"\fvolume_group\x18\x01 \x01(\v2\x18.volumegroup.VolumeGroupR\vvolumeGroup:\x03\xf0D\x01\"\xe4\x01\n" +
	"\x1fControllerGetVolumeGroupRequest\x12&\n" +
	"\x0fvolume_group_id\x18\x01 \x01(\tR\rvolumeGroupId\x12X\n" +
	"\asecrets\x18\x02 \x03(\v29.volumegroup.ControllerGetVolumeGroupRequest.SecretsEntryB\x03\xe8D\x01R\asecrets\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\x03\xf0D\x01\"d\n" +
	" ControllerGetVolumeGroupResponse\x12;\n" +
	"\fvolume_group\x18\x01 \x01(\v2\x18.volumegroup.VolumeGroupR\vvolumeGroup:\x03\xf0D\x01\"\xf4\x01\n" +
	"\x17ListVolumeGroupsRequest\x12\x1f\n" +
	"\vmax_entries\x18\x01 \x01(\x05R\n" +
	"maxEntries\x12%\n" +
	"\x0estarting_token\x18\x02 \x01(\tR\rstartingToken\x12P\n" +
	"\asecrets\x18\x03 \x03(\v21.volumegroup.ListVolumeGroupsRequest.SecretsEntryB\x03\xe8D\x01R\asecrets\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\x03\xf0D\x01\"\xcb\x01\n" +
	"\x18ListVolumeGroupsResponse\x12E\n" +
	"\aentries\x18\x01 \x03(\v2+.volumegroup.ListVolumeGroupsResponse.EntryR\aentries\x12\x1d\n" +
	"\n" +
	"next_token\x18\x02 \x01(\tR\tnextToken\x1aD\n" +
	"\x05Entry\x12;\n" +
	"\fvolume_group\x18\x01 \x01(\v2\x18.volumegroup.VolumeGroupR\vvolumeGroup:\x03\xf0D\x012\xca\x04\n" +
	"\n" +
	"Controller\x12g\n" +
	"\x11CreateVolumeGroup\x12%.volumegroup.CreateVolumeGroupRequest\x1a&.volumegroup.CreateVolumeGroupResponse\"\x03\xf0D\x01\x12\x85\x01\n" +
	"\x1bModifyVolumeGroupMembership\x12/.volumegroup.ModifyVolumeGroupMembershipRequest\x1a0.volumegroup.ModifyVolumeGroupMembershipResponse\"\x03\xf0D\x01\x12g\n" +
	"\x11DeleteVolumeGroup\x12%.volumegroup.DeleteVolumeGroupRequest\x1a&.volumegroup.DeleteVolumeGroupResponse\"\x03\xf0D\x01\x12d\n" +
	"\x10ListVolumeGroups\x12$.volumegroup.ListVolumeGroupsRequest\x1a%.volumegroup.ListVolumeGroupsResponse\"\x03\xf0D\x01\x12|\n" +
	"\x18ControllerGetVolumeGroup\x12,.volumegroup.ControllerGetVolumeGroupRequest\x1a-.volumegroup.ControllerGetVolumeGroupResponse\"\x03\xf0D\x01:B\n" +
	"\rvg_csi_secret\x12\x1d.google.protobuf.FieldOptions\x18\xcd\b \x01(\bR\vvgCsiSecret:J\n" +
	"\x10vg_alpha_message\x12\x1f.google.protobuf.MessageOptions\x18\xce\b \x01(\bR\x0evgAlphaMessage:G\n" +
	"\x0fvg_alpha_method\x12\x1e.google.protobuf.MethodOptions\x18\xce\b \x01(\bR\rvgAlphaMethodB\x0fZ\r.;volumegroupb\x06proto3"

var (
	file_volumegroup_volumegroup_proto_rawDescOnce sync.Once
	file_volumegroup_volumegroup_proto_rawDescData []byte
)

func file_volumegroup_volumegroup_proto_rawDescGZIP() []byte {
	file_volumegroup_volumegroup_proto_rawDescOnce.Do(func() {
		file_volumegroup_volumegroup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_volumegroup_volumegroup_proto_rawDesc), len(file_volumegroup_volumegroup_proto_rawDesc)))
	})
	return file_volumegroup_volumegroup_proto_rawDescData
}

var file_volumegroup_volumegroup_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_volumegroup_volumegroup_proto_goTypes = []any{
	(*CreateVolumeGroupRequest)(nil),            // 0: volumegroup.CreateVolumeGroupRequest
	(*CreateVolumeGroupResponse)(nil),           // 1: volumegroup.CreateVolumeGroupResponse
	(*VolumeGroup)(nil),                         // 2: volumegroup.VolumeGroup
	(*VgVolume)(nil),                            // 3: volumegroup.VgVolume
	(*VgTopology)(nil),                          // 4: volumegroup.VgTopology
	(*VgVolumeContentSource)(nil),               // 5: volumegroup.VgVolumeContentSource
	(*DeleteVolumeGroupRequest)(nil),            // 6: volumegroup.DeleteVolumeGroupRequest
	(*DeleteVolumeGroupResponse)(nil),           // 7: volumegroup.DeleteVolumeGroupResponse
	(*ModifyVolumeGroupMembershipRequest)(nil),  // 8: volumegroup.ModifyVolumeGroupMembershipRequest
	(*ModifyVolumeGroupMembershipResponse)(nil), // 9: volumegroup.ModifyVolumeGroupMembershipResponse
	(*ControllerGetVolumeGroupRequest)(nil),     // 10: volumegroup.ControllerGetVolumeGroupRequest
	(*ControllerGetVolumeGroupResponse)(nil),    // 11: volumegroup.ControllerGetVolumeGroupResponse
	(*ListVolumeGroupsRequest)(nil),             // 12: volumegroup.ListVolumeGroupsRequest
	(*ListVolumeGroupsResponse)(nil),            // 13: volumegroup.ListVolumeGroupsResponse
	nil,                                         // 14: volumegroup.CreateVolumeGroupRequest.ParametersEntry
	nil,                                         // 15: volumegroup.CreateVolumeGroupRequest.SecretsEntry
	nil,                                         // 16: volumegroup.VolumeGroup.VolumeGroupContextEntry
	nil,                                         // 17: volumegroup.VgVolume.VolumeContextEntry
	nil,                                         // 18: volumegroup.VgTopology.SegmentsEntry
	(*VgVolumeContentSource_SnapshotSource)(nil), // 19: volumegroup.VgVolumeContentSource.SnapshotSource
	(*VgVolumeContentSource_VolumeSource)(nil),   // 20: volumegroup.VgVolumeContentSource.VolumeSource
	nil,                                    // 21: volumegroup.DeleteVolumeGroupRequest.SecretsEntry
	nil,                                    // 22: volumegroup.ModifyVolumeGroupMembershipRequest.SecretsEntry
	nil,                                    // 23: volumegroup.ControllerGetVolumeGroupRequest.SecretsEntry
	nil,                                    // 24: volumegroup.ListVolumeGroupsRequest.SecretsEntry
	(*ListVolumeGroupsResponse_Entry)(nil), // 25: volumegroup.ListVolumeGroupsResponse.Entry
	(*descriptorpb.FieldOptions)(nil),      // 26: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil),    // 27: google.protobuf.MessageOptions
	(*descriptorpb.MethodOptions)(nil),     // 28: google.protobuf.MethodOptions
}
var file_volumegroup_volumegroup_proto_depIdxs = []int32{
	14, // 0: volumegroup.CreateVolumeGroupRequest.parameters:type_name -> volumegroup.CreateVolumeGroupRequest.ParametersEntry
	15, // 1: volumegroup.CreateVolumeGroupRequest.secrets:type_name -> volumegroup.CreateVolumeGroupRequest.SecretsEntry
	2,  // 2: volumegroup.CreateVolumeGroupResponse.volume_group:type_name -> volumegroup.VolumeGroup
	16, // 3: volumegroup.VolumeGroup.volume_group_context:type_name -> volumegroup.VolumeGroup.VolumeGroupContextEntry
	3,  // 4: volumegroup.VolumeGroup.volumes:type_name -> volumegroup.VgVolume
	17, // 5: volumegroup.VgVolume.volume_context:type_name -> volumegroup.VgVolume.VolumeContextEntry
	5,  // 6: volumegroup.VgVolume.content_source:type_name -> volumegroup.VgVolumeContentSource
	4,  // 7: volumegroup.VgVolume.accessible_topology:type_name -> volumegroup.VgTopology
	18, // 8: volumegroup.VgTopology.segments:type_name -> volumegroup.VgTopology.SegmentsEntry
	19, // 9: volumegroup.VgVolumeContentSource.snapshot:type_name -> volumegroup.VgVolumeContentSource.SnapshotSource
	20, // 10: volumegroup.VgVolumeContentSource.volume:type_name -> volumegroup.VgVolumeContentSource.VolumeSource
	21, // 11: volumegroup.DeleteVolumeGroupRequest.secrets:type_name -> volumegroup.DeleteVolumeGroupRequest.SecretsEntry
	22, // 12: volumegroup.ModifyVolumeGroupMembershipRequest.secrets:type_name -> volumegroup.ModifyVolumeGroupMembershipRequest.SecretsEntry
	2,  // 13: volumegroup.ModifyVolumeGroupMembershipResponse.volume_group:type_name -> volumegroup.VolumeGroup
	23, // 14: volumegroup.ControllerGetVolumeGroupRequest.secrets:type_name -> volumegroup.ControllerGetVolumeGroupRequest.SecretsEntry
	2,  // 15: volumegroup.ControllerGetVolumeGroupResponse.volume_group:type_name -> volumegroup.VolumeGroup
	24, // 16: volumegroup.ListVolumeGroupsRequest.secrets:type_name -> volumegroup.ListVolumeGroupsRequest.SecretsEntry
	25, // 17: volumegroup.ListVolumeGroupsResponse.entries:type_name -> volumegroup.ListVolumeGroupsResponse.Entry
	2,  // 18: volumegroup.ListVolumeGroupsResponse.Entry.volume_group:type_name -> volumegroup.VolumeGroup
	26, // 19: volumegroup.vg_csi_secret:extendee -> google.protobuf.FieldOptions
	27, // 20: volumegroup.vg_alpha_message:extendee -> google.protobuf.MessageOptions
	28, // 21: volumegroup.vg_alpha_method:extendee -> google.protobuf.MethodOptions
	0,  // 22: volumegroup.Controller.CreateVolumeGroup:input_type -> volumegroup.CreateVolumeGroupRequest
	8,  // 23: volumegroup.Controller.ModifyVolumeGroupMembership:input_type -> volumegroup.ModifyVolumeGroupMembershipRequest
	6,  // 24: volumegroup.Controller.DeleteVolumeGroup:input_type -> volumegroup.DeleteVolumeGroupRequest
	12, // 25: volumegroup.Controller.ListVolumeGroups:input_type -> volumegroup.ListVolumeGroupsRequest
	10, // 26: volumegroup.Controller.ControllerGetVolumeGroup:input_type -> volumegroup.ControllerGetVolumeGroupRequest
	1,  // 27: volumegroup.Controller.CreateVolumeGroup:output_type -> volumegroup.CreateVolumeGroupResponse
	9,  // 28: volumegroup.Controller.ModifyVolumeGroupMembership:output_type -> volumegroup.ModifyVolumeGroupMembershipResponse
	7,  // 29: volumegroup.Controller.DeleteVolumeGroup:output_type -> volumegroup.DeleteVolumeGroupResponse
	13, // 30: volumegroup.Controller.ListVolumeGroups:output_type -> volumegroup.ListVolumeGroupsResponse
	11, // 31: volumegroup.Controller.ControllerGetVolumeGroup:output_type -> volumegroup.ControllerGetVolumeGroupResponse
	27, // [27:32] is the sub-list for method output_type
	22, // [22:27] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	19, // [19:22] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_volumegroup_volumegroup_proto_init() }
func file_volumegroup_volumegroup_proto_init() {
	if File_volumegroup_volumegroup_proto != nil {
		return
	}
	file_volumegroup_volumegroup_proto_msgTypes[5].OneofWrappers = []any{
		(*VgVolumeContentSource_Snapshot)(nil),
		(*VgVolumeContentSource_Volume)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_volumegroup_volumegroup_proto_rawDesc), len(file_volumegroup_volumegroup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 3,
			NumServices:   1,
		},
		GoTypes:           file_volumegroup_volumegroup_proto_goTypes,
		DependencyIndexes: file_volumegroup_volumegroup_proto_depIdxs,
		MessageInfos:      file_volumegroup_volumegroup_proto_msgTypes,
		ExtensionInfos:    file_volumegroup_volumegroup_proto_extTypes,
	}.Build()
	File_volumegroup_volumegroup_proto = out.File
	file_volumegroup_volumegroup_proto_goTypes = nil
	file_volumegroup_volumegroup_proto_depIdxs = nil
}
